# Feel free to modify this. Use spigot/bukkit material names 
#(https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html). 

Cauldron Cooking uses Water: true
Throwable Fire Charges: true
Burning Blocks make Ash: true

# Chance for ash to become flint. 0.1 = 10%. Set to 0 to disable ash dropping flint
Ash Flint Chance: 0.1

# Chance for ash to be created when "solid" (logs, leaves, coal, etc) blocks are burnt down
Ash Creation Chance: 0.6

# Chance for ash to be created when "passable" (grass, trapdoors, etc) blocks are burnt down
Passable Ash Creation Chance: 0.3

# Cumulative chance for ash to drop experience. If it is 0.4, the chance to drop 2 orbs is 0.16 (0.4^2). Do not set to 1
Cumulative Ash Experience Chance: 0.4

#All materials that can "Hot Blocks"
HeatableMaterials:
- IRON_BLOCK
- GOLD_BLOCK
- SMOOTH_STONE
- ANDESITE
- DIORITE
- GRANITE
- CAULDRON
- HOPPER
- WATER

#Items a cauldron can cook. They must already have a furnace recipe (though datapack recipes are supported) 
CauldronCookables:
- BAKED_POTATO
- MUTTON
- BEEF
- PORKCHOP
- CHICKEN
- SALMON
- COD
- CHORUS_FRUIT
- RABBIT

#Blocks that will burn twice as long
LongBurns:
- ACACIA_PLANKS
- BIRCH_PLANKS
- DARK_OAK_PLANKS
- JUNGLE_PLANKS
- OAK_PLANKS
- SPRUCE_PLANKS
#Blocks that will burn three times as long
LongerBurns:
- ACACIA_LOG
- BIRCH_LOG
- DARK_OAK_LOG
- JUNGLE_LOG
- OAK_LOG
- SPRUCE_LOG
#Blocks that will burn five times as long
ExtremelyLongBurns:
- COAL_BLOCK
