name: EnhancedFire
main: com.SketchyPlugins.EnhancedFire.Main
version: 0.0.5
api-version: 1.13
author: Pop101
description: Changes fire mechanics to make it more useful but also more dangerous...
permissions:
   EnhancedFire.immunity:
      description: Provides immunity from all hot blocks
      default: false
      children:
         EnhancedFire.immunity.blocks: true
         EnhancedFire.immunity.water: true
         EnhancedFire.immunity.fire: true
         EnhancedFire.immunity.lava: true
   EnhancedFire.immunity.blocks:
      description: Provides immunity from dry, heated blocks
      default: false
   EnhancedFire.immunity.water:
      description: Provides immunity from heated water and cauldrons
      default: false
   EnhancedFire.immunity.fire:
      description: Provides immunity from fire damage, but not from being ignited
      default: false
   EnhancedFire.immunity.lava:
      description: Provides immunity from swimming in lava
      default: false