name: EnhancedFire
main: com.SketchyPlugins.EnhancedFire.Main
version: 0.0.5
api-version: 1.13
author: Pop101
description: Changes fire mechanics to make it more useful but also more dangerous...
permissions:
   EnhancedFire.immunity:
      description: Provides immunity from all hot blocks
      default: none
   EnhancedFire.immunity.blocks:
      description: Provides immunity from dry, heated blocks
      default: none
   EnhancedFire.immunity.water:
      description: Provides immunity from heated water and cauldrons
      default: none
